"""
State registry — configuration for all US sports betting states.
Built from research/state_data_research.xlsx.
"""

STATE_REGISTRY = {
    'NY': {
        'name': 'New York',
        'regulatory_body': 'NY State Gaming Commission',
        'source_url': 'https://gaming.ny.gov/revenue-reports',
        'frequency': 'weekly',
        'skip_weekly_aggregation': True,
        'format': 'xlsx',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.51,
        'retail_tax_rate': 0.10,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': False,
        'launch_date': '2022-01-08',
        'tier': 1,
    },
    'IL': {
        'name': 'Illinois',
        'regulatory_body': 'Illinois Gaming Board',
        'source_url': 'https://igb.illinois.gov/sports-wagering/sports-reports.html',
        'frequency': 'monthly',
        'format': 'csv',
        'has_operator_breakdown': True,
        'has_sport_breakdown': True,
        'has_channel_split': True,
        'online_tax_rate': None,  # Graduated 20-40%
        'retail_tax_rate': None,  # Graduated 20-40%
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': False,
        'launch_date': '2020-03-09',
        'tier': 1,
        'reports_handle': True,
        'notes': 'Graduated tax: 20% (<$30M), 25% ($30-50M), 30% ($50-100M), 35% ($100-200M), 40% (>$200M). Plus per-wager surcharge starting July 2025. Handle and GGR from Completed Events Detail CSV; AGR/tax from Tax Summary CSV; sport handle from Sport Detail CSV.',
    },
    'PA': {
        'name': 'Pennsylvania',
        'regulatory_body': 'PA Gaming Control Board',
        'source_url': 'https://gamingcontrolboard.pa.gov/news-and-transparency/revenue',
        'frequency': 'monthly',
        'format': 'xlsx',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.36,
        'retail_tax_rate': 0.36,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2018-11-17',
        'tier': 1,
    },
    'NJ': {
        'name': 'New Jersey',
        'regulatory_body': 'NJ Division of Gaming Enforcement',
        'source_url': 'https://www.njoag.gov/about/divisions-and-offices/division-of-gaming-enforcement-home/financial-and-statistical-information/',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.1975,  # Raised from 0.13 in July 2025
        'retail_tax_rate': 0.085,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': True,
        'promo_notes': 'Limited: only >$7.5M/month',
        'launch_date': '2018-06-14',
        'tier': 1,
        'reports_handle': False,
        'sport_categories': ['Football', 'Basketball', 'Baseball', 'Parlay', 'Other'],
    },
    'OH': {
        'name': 'Ohio',
        'regulatory_body': 'Ohio Casino Control Commission',
        'source_url': 'https://casinocontrol.ohio.gov/about/revenue-reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.20,
        'retail_tax_rate': 0.20,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': False,
        'promo_notes': 'Not deductible until 2027 (10%), then 2032 (20%)',
        'launch_date': '2023-01-01',
        'tier': 1,
    },
    'MI': {
        'name': 'Michigan',
        'regulatory_body': 'MI Gaming Control Board',
        'source_url': 'https://www.michigan.gov/mgcb/detroit-casinos/resources/revenues-and-wagering-tax-information',
        'frequency': 'monthly',
        'format': 'xlsx',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.084,
        'retail_tax_rate': 0.084,
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'promo_notes': 'Fully deductible (unlimited)',
        'launch_date': '2021-01-22',
        'tier': 1,
    },
    'AZ': {
        'name': 'Arizona',
        'regulatory_body': 'Arizona Department of Gaming',
        'source_url': 'https://gaming.az.gov/blog-terms/event-wagering-revenue-reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.10,
        'retail_tax_rate': 0.08,
        'tax_basis': 'adjusted_gross_receipts',
        'promo_deduction_allowed': True,
        'promo_notes': 'Sliding scale: Yrs 1-2: 20%, Yr 3: 15%, Yrs 4-5: 10%, Yr 6+: 0%',
        'launch_date': '2021-09-09',
        'tier': 4,
        'ggr_definition': 'Adjusted Gross EW Receipts (Handle − Payouts − Federal Excise Tax, before promo deductions)',
        'standard_ggr_notes': (
            'AZ reports "Adjusted Gross Event Wagering Receipts" = Handle − Payouts − '
            'Federal Excise Tax (0.25% of handle). Standard GGR = Handle − Payouts, adding '
            'excise back. Difference is ~0.25% of handle. The federal excise tax is a cost '
            'of doing business, not a payout to bettors. Actual excise amounts extracted '
            'from PDF (implied as standard_ggr − gross_revenue) rather than estimated at 0.25%.'
        ),
    },
    'IN': {
        'name': 'Indiana',
        'regulatory_body': 'Indiana Gaming Commission',
        'source_url': 'https://www.in.gov/igc/publications/monthly-revenue/',
        'frequency': 'monthly',
        'format': 'xlsx',
        'has_operator_breakdown': True,
        'has_sport_breakdown': True,
        'has_channel_split': True,
        'online_tax_rate': 0.095,
        'retail_tax_rate': 0.095,
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'promo_notes': '$7M cap annually per licensee',
        'launch_date': '2019-09-01',
        'tier': 2,
    },
    'MA': {
        'name': 'Massachusetts',
        'regulatory_body': 'Massachusetts Gaming Commission',
        'source_url': 'https://massgaming.com/regulations/revenue/',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.20,
        'retail_tax_rate': 0.15,
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2023-01-31',
        'tier': 2,
    },
    'MD': {
        'name': 'Maryland',
        'regulatory_body': 'Maryland Lottery and Gaming Control Agency',
        'source_url': 'https://www.mdgaming.com/maryland-sports-wagering/revenue-reports/',
        'frequency': 'monthly',
        'format': 'html',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.20,
        'retail_tax_rate': 0.15,
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2021-12-10',
        'tier': 2,
    },
    'VA': {
        'name': 'Virginia',
        'regulatory_body': 'Virginia Lottery',
        'source_url': 'https://www.valottery.com/aboutus/casinosandsportsbetting/sportsbetting',
        'frequency': 'monthly',
        'format': 'html',
        'has_operator_breakdown': False,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.15,
        'retail_tax_rate': 0.15,
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'promo_notes': 'Only during first 12 months of operation',
        'launch_date': '2021-01-21',
        'tier': 2,
        'notes': 'Data from VA Lottery press releases API. Mobile + Casino Retail (casinos started Jan 2023). 11+ mobile operators, 3+ retail casinos. Early reports (Jan-Apr 2021) text-only.',
    },
    'CO': {
        'name': 'Colorado',
        'regulatory_body': 'Colorado Division of Gaming',
        'source_url': 'https://sbg.colorado.gov/sports-betting-monthly-reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': True,
        'has_channel_split': True,
        'online_tax_rate': 0.10,
        'retail_tax_rate': 0.10,
        'tax_basis': 'net_sports_betting_proceeds',
        'promo_deduction_allowed': True,
        'promo_notes': 'Sunset via HB25-1311: stepping down to 0% by July 2026',
        'launch_date': '2020-05-01',
        'tier': 2,
        'ggr_definition': 'Gross Gaming Revenue (Handle − Payouts, before promo deductions)',
        'standard_ggr_notes': (
            'CO reports GGR = Handle − Payouts (no excise deduction). Standard GGR equals '
            'reported GGR. NSBP (Net Sports Betting Proceeds) = GGR − promo deductions, '
            'which is what gets taxed at 10%. Two report types: Monthly Summary (handle/GGR, '
            'image-based PDFs needing OCR) and HB 1292 (NSBP/tax by city, text-based).'
        ),
    },
    'CT': {
        'name': 'Connecticut',
        'regulatory_body': 'CT DCP Gaming Division',
        'source_url': 'https://data.ct.gov/api/views/xf6g-659c/rows.csv?accessType=DOWNLOAD',
        'frequency': 'monthly',
        'format': 'csv',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.1375,
        'retail_tax_rate': 0.1375,
        'tax_basis': 'gross_gaming_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2021-10-19',
        'tier': 3,
    },
    'KY': {
        'name': 'Kentucky',
        'regulatory_body': 'KY Horse Racing Commission',
        'source_url': 'https://khrc.ky.gov/newstatic_info.aspx?static_ID=694',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.1425,
        'retail_tax_rate': 0.0975,
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2023-09-28',
        'tier': 3,
    },
    'TN': {
        'name': 'Tennessee',
        'regulatory_body': 'Sports Wagering Advisory Council',
        'source_url': 'https://www.tn.gov/swac/reports.html',
        'frequency': 'monthly',
        'format': 'csv',
        'has_operator_breakdown': False,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.0185,  # On HANDLE, not GGR!
        'retail_tax_rate': None,
        'tax_basis': 'handle',  # CRITICAL: Taxes handle, not GGR!
        'promo_deduction_allowed': False,
        'launch_date': '2020-11-01',
        'tier': 3,
        'notes': 'ONLY state that taxes HANDLE (1.85%) instead of GGR. Online only. GGR/payouts reported pre-Jul 2023 (20% AGI tax era); post-Jul 2023 only handle+tax reported, GGR estimated at 10% hold.',
    },
    'LA': {
        'name': 'Louisiana',
        'regulatory_body': 'LA Gaming Control Board / LSP Gaming Enforcement',
        'source_url': 'https://lsp.org/about/leadershipsections/bureau-of-investigations/gaming-enforcement-division/',
        'frequency': 'monthly',
        'format': 'xlsx',
        'has_operator_breakdown': False,
        'has_sport_breakdown': True,
        'has_channel_split': True,
        'online_tax_rate': 0.215,
        'retail_tax_rate': 0.10,
        'tax_basis': 'adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2021-07-01',
        'tier': 3,
        'sport_categories': ['Baseball', 'Basketball', 'Football', 'Soccer', 'Parlay', 'Other'],
        'launch_notes': 'Retail launched Oct 28, 2021 officially, but some casinos accepted bets from Jul 2021 under temporary authorization. Online launched Jan 28, 2022.',
    },
    'NC': {
        'name': 'North Carolina',
        'regulatory_body': 'NC State Lottery Commission / NC Gaming Commission',
        'source_url': 'https://ncgaming.gov/about/reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.18,
        'retail_tax_rate': None,
        'tax_basis': 'gross_wagering_revenue',
        'promo_deduction_allowed': False,
        'launch_date': '2024-03-11',
        'tier': 2,
        'notes': 'Online only. Promos tracked but NOT deductible.',
    },
    'KS': {
        'name': 'Kansas',
        'regulatory_body': 'Kansas Lottery',
        'source_url': 'https://www.kslottery.com/publications/sports-monthly-revenues/',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.10,
        'retail_tax_rate': 0.10,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2022-09-01',
        'tier': 3,
    },
    'IA': {
        'name': 'Iowa',
        'regulatory_body': 'Iowa Racing and Gaming Commission',
        'source_url': 'https://irgc.iowa.gov/publications-reports/sports-wagering-revenue',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.0675,
        'retail_tax_rate': 0.0675,
        'tax_basis': 'net_receipts',
        'promo_deduction_allowed': True,
        'launch_date': '2019-08-15',
        'tier': 3,
        'notes': 'PDFs: page 1 = per-casino retail+internet, page 2 = per-operator online. ~19 casinos, ~13 online operators. FY archive PDFs (FY2020-FY2025) for backfill; monthly PDFs for current FY. Online operator pages start FY2022.',
    },
    'WV': {
        'name': 'West Virginia',
        'regulatory_body': 'WV Lottery Commission',
        'source_url': 'https://business.wvlottery.com/resourcesPayments',
        'frequency': 'weekly',
        'format': 'zip',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.10,
        'retail_tax_rate': 0.10,
        'tax_basis': 'adjusted_gross_receipts',
        'promo_deduction_allowed': False,
        'launch_date': '2018-08-30',
        'tier': 4,
        'notes': 'Data is by casino venue (Mountaineer, Wheeling, Mardi Gras, Charles Town, Greenbrier), NOT by sportsbook brand. Each venue hosts multiple sportsbook skins under one master license. Cannot map venues to individual operators like DraftKings/FanDuel.',
    },
    'ME': {
        'name': 'Maine',
        'regulatory_body': 'Maine Gambling Control Unit',
        'source_url': 'https://www.maine.gov/dps/gcu/sports-wagering/sports-wagering-revenue',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.16,
        'retail_tax_rate': 0.10,
        'tax_basis': 'adjusted_gross_receipts',
        'promo_deduction_allowed': True,
        'launch_date': '2023-11-03',
        'tier': 4,
        'notes': '4 tribal operators: DraftKings (Passamaquoddy), Caesars (Penobscot/Maliseet/Mi\'kmaq). Plus Oxford Casino and First Tracks retail.',
    },
    'NH': {
        'name': 'New Hampshire',
        'regulatory_body': 'NH Lottery Commission',
        'source_url': 'https://www.nhlottery.com/About-Us/Financial-Reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.51,
        'retail_tax_rate': 0.51,
        'tax_basis': 'revenue_share',
        'promo_deduction_allowed': False,
        'launch_date': '2019-12-01',
        'tier': 4,
        'notes': 'DraftKings sole operator. 51% revenue share to state.',
    },
    'RI': {
        'name': 'Rhode Island',
        'regulatory_body': 'Rhode Island Lottery',
        'source_url': 'https://www.rilot.com/en-us/about-us/financials.html',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.51,
        'retail_tax_rate': 0.51,
        'tax_basis': 'revenue_share',
        'promo_deduction_allowed': False,
        'launch_date': '2018-11-26',
        'tier': 4,
        'notes': 'Monopoly: IGT/Bally\'s under Lottery oversight. Revenue split: State 51%, IGT 32%, Bally\'s 17%. Three venues: Twin River (retail), Tiverton Casino (retail), Online (Mobile).',
    },
    'WY': {
        'name': 'Wyoming',
        'regulatory_body': 'Wyoming Gaming Commission',
        'source_url': 'https://gaming.wyo.gov/revenue-reports/financial-reports/combined-wagering-activity-reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.10,
        'retail_tax_rate': None,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2021-09-01',
        'tier': 4,
        'notes': 'Online only. 5 operators.',
    },
    'MO': {
        'name': 'Missouri',
        'regulatory_body': 'Missouri Gaming Commission',
        'source_url': 'https://www.mgc.dps.mo.gov/SportsWagering/sw_financials/rb_SWFin_main.html',
        'frequency': 'monthly',
        'format': 'xlsx',
        'has_operator_breakdown': True,
        'has_sport_breakdown': True,
        'has_channel_split': True,
        'online_tax_rate': 0.10,
        'retail_tax_rate': 0.10,
        'tax_basis': 'taxable_adjusted_gross_revenue',
        'promo_deduction_allowed': True,
        'promo_notes': 'Up to 25% of revenue deductible for free bets/promos',
        'launch_date': '2025-12-01',
        'tier': 3,
        'sport_categories': ['Baseball', 'Basketball', 'Boxing/MMA', 'Football', 'Hockey', 'Soccer', 'Tennis', 'Motor Racing', 'Parlay', 'Other'],
    },
    'MT': {
        'name': 'Montana',
        'regulatory_body': 'Montana Lottery',
        'source_url': 'https://sportsbetmontana.com/en/view/news',
        'frequency': 'weekly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': True,
        'has_channel_split': False,
        'online_tax_rate': None,
        'retail_tax_rate': None,
        'tax_basis': 'revenue_share',
        'promo_deduction_allowed': False,
        'launch_date': '2020-03-01',
        'tier': 5,
        'notes': 'State monopoly via Intralot. ~8.5% effective rate. Retail only (Intralot terminals in bars/restaurants). Weekly + monthly PDFs from sportsbetmontana.com.',
    },
    'OR': {
        'name': 'Oregon',
        'regulatory_body': 'Oregon Lottery',
        'source_url': 'https://digitalcollections.library.oregon.gov/nodes/view/224705',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': True,
        'has_channel_split': False,
        'online_tax_rate': None,
        'retail_tax_rate': None,
        'tax_basis': 'revenue_share',
        'promo_deduction_allowed': False,
        'launch_date': '2019-10-01',
        'tier': 5,
        'sport_categories': ['Baseball', 'Basketball', 'Football', 'Hockey', 'Soccer', 'Table_Tennis', 'Tennis', 'Other'],
        'notes': 'DraftKings sole online operator via Lottery Scoreboard. Online only. Monthly PDFs from Oregon Digital Collections. ~8% revenue share.',
    },
    'SD': {
        'name': 'South Dakota',
        'regulatory_body': 'SD Department of Revenue',
        'source_url': 'https://dor.sd.gov/businesses/gaming/',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': True,
        'has_channel_split': False,
        'online_tax_rate': None,
        'retail_tax_rate': 0.09,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': False,
        'launch_date': '2021-09-01',
        'tier': 5,
        'notes': 'Deadwood casinos only. Retail only. ~$10M/yr handle.',
    },
    'DE': {
        'name': 'Delaware',
        'regulatory_body': 'Delaware Lottery',
        'source_url': 'https://www.delottery.com/Sports-Lottery',
        'frequency': 'monthly',
        'format': 'html',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': None,
        'retail_tax_rate': None,
        'tax_basis': 'revenue_share',
        'promo_deduction_allowed': False,
        'launch_date': '2018-06-05',
        'tier': 5,
        'notes': 'First state post-PASPA. Lottery model. ~50% effective rate.',
    },
    'DC': {
        'name': 'District of Columbia',
        'regulatory_body': 'DC Office of Lottery and Gaming',
        'source_url': 'https://dclottery.com/olg/financials',
        'frequency': 'monthly',
        'format': 'html',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': True,
        'online_tax_rate': 0.30,
        'retail_tax_rate': 0.10,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2020-05-28',
        'tier': 5,
        'notes': 'HTML tables per month. 3 operator classes: A (stadium, 10% tax), B (retail bars, 10% tax), C (mobile/online, 30% tax). ~68 reports from Jul 2020.',
    },
    'AR': {
        'name': 'Arkansas',
        'regulatory_body': 'AR Racing Commission / DFA',
        'source_url': 'https://www.dfa.arkansas.gov/',
        'frequency': 'annual',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.13,
        'retail_tax_rate': 0.13,
        'tax_basis': 'net_gaming_receipts',
        'promo_deduction_allowed': True,
        'launch_date': '2019-04-01',
        'tier': 5,
        'notes': 'Tiered: 13% up to $150M, 20% above. Sports + casino combined in reports. First casino (Oaklawn) opened Apr 2019, second (Southland) Jul 2019.',
    },
    'VT': {
        'name': 'Vermont',
        'regulatory_body': 'VT Dept of Liquor & Lottery',
        'source_url': 'https://liquorandlottery.vermont.gov/sports-wagering-reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': 0.20,
        'retail_tax_rate': None,
        'tax_basis': 'adjusted_gross_sports_wagering_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '2024-01-11',
        'tier': 5,
        'notes': 'Online only. Single operator platform with 6 skins (3 active: FanDuel, DraftKings, Fanatics). 20% tax on adj gross revenue + 31.7% revenue share to state.',
    },
    'MS': {
        'name': 'Mississippi',
        'regulatory_body': 'MS Gaming Commission',
        'source_url': 'https://www.msgamingcommission.com/reports/monthly_reports',
        'frequency': 'monthly',
        'format': 'xlsx',
        'has_operator_breakdown': False,
        'has_sport_breakdown': True,
        'has_channel_split': False,
        'online_tax_rate': None,
        'retail_tax_rate': 0.12,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': False,
        'launch_date': '2018-08-01',
        'tier': 5,
        'notes': 'Casino-based retail only. No statewide mobile. 3-region breakdown. 8% state + 4% local tax.',
    },
    'NV': {
        'name': 'Nevada',
        'regulatory_body': 'Nevada Gaming Control Board',
        'source_url': 'https://www.gaming.nv.gov/about-us/gaming-revenue-information-gri/',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': False,
        'has_sport_breakdown': True,
        'has_channel_split': False,
        'online_tax_rate': 0.0675,
        'retail_tax_rate': 0.0675,
        'tax_basis': 'gross_revenue',
        'promo_deduction_allowed': True,
        'launch_date': '1949-01-01',
        'tier': 5,
        'notes': 'Sports data embedded in comprehensive 48-page GRI report. Win in THOUSANDS. Handle not directly reported.',
    },
    'NE': {
        'name': 'Nebraska',
        'regulatory_body': 'Nebraska Racing & Gaming Commission',
        'source_url': 'https://nrgc.nebraska.gov/gaming/reports',
        'frequency': 'monthly',
        'format': 'pdf',
        'has_operator_breakdown': True,
        'has_sport_breakdown': False,
        'has_channel_split': False,
        'online_tax_rate': None,
        'retail_tax_rate': 0.20,
        'tax_basis': 'gross_gaming_revenue',
        'promo_deduction_allowed': False,
        'launch_date': '2023-05-01',
        'tier': 5,
        'reports_handle': False,
        'notes': 'Retail only (no online). 5 facilities with sports betting: WarHorse Lincoln, WarHorse Omaha, Grand Island Casino Resort, Harrahs Columbus, Lake Mac Casino & Resort. 20% tax on Total GGR (combined sports+slots+tables; cannot isolate sports-only tax). PDFs report GGR and tax only — no handle or payouts breakdown. Revenue Breakdown PDFs (one per year) contain monthly data for all operators.',
    },
}


def get_state_config(state_code: str) -> dict:
    """Get configuration for a state code."""
    return STATE_REGISTRY.get(state_code.upper())


def get_all_states() -> list[str]:
    """Get list of all state codes."""
    return sorted(STATE_REGISTRY.keys())


def get_states_by_tier(tier: int) -> list[str]:
    """Get state codes for a specific tier."""
    return sorted(code for code, cfg in STATE_REGISTRY.items() if cfg.get('tier') == tier)
